### PR TITLE
Adding smart contract for voting dapp

### PR DESCRIPTION
**Pull request by gurusinb**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## What features have been added or changed/Fixed(In Points)(Required)
-
-

## Type of change(Required)

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist(Required):

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Output Screenshots(Required)

### CODE REVIEW

**Comment by mbcse** [comment]
@gurusinb Please fill the pull request template and also make an issue for this and link that issue here

**Comment by mbcse** [comment]
@gurusinb The contract is also not perfect and does not include all functions. Please solve the issues I have raised and complete the contract into a fully implementable election contract

**Comment by gurusinb** [comment]
What other functions are required? Please help.

**Comment by mbcse** [comment]
> What other functions are required? Please help.

Functions like banning candidates, adding voting period, etc. You can search for multiple implementations of election contracts on internet, club them and make a single all rounder one

**Pull request closed without merging**
