### PR TITLE
Bank Smart Contract Created.

### LINKED ISSUE #10: Create a bank smart contract
Make a contract where a user can deposit, withdraw funds, etc like in bank. Add more functions by researching what additional things can be added apart from basic banking operations

### PR DESCRIPTION
**Pull request by belelaritra**
# Bank Smart Contract

Here is a simple bank smart contract where you can 
1. Create Account 
2. Deposit Ether & convert it into account balance
3. Withdraw from account.
4. Transfer balance (Within Bank)
5. Check account balance & details.

After you request for amount withdraw, your `available balance` will be reduced by the amount you requested & `pending balance` will be the previous `available balance`  until the transaction is approved by the bank else it will be reverted back to your account. (Just Like : NEFT/ RTGS)

Fixes #10

## What features have been added or changed/Fixed(In Points)(Required)
- Smart Contract Created

## Blockchain this work is compatible with(Required)
- Ethereum
- Solidity v0.5.16

## Type of change(Required)
- [x] New feature (non-breaking change which adds functionality)

# Checklist(Required):

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Output Screenshots(Required)
### 1. Account Created : 
Account Created

<table>
  <tr>
    <td>
 2. Deposit Ether (wei) : 
Ether Deposit
</td>
<td>
 3. Account Balance after Deposit :
Account Details
</td>
<tr>
      <td>
 4. Withdraw Request :
Screenshot 2022-02-03 at 4 32 30 AM
</td>
<td>
 Account Balance after Withdrawl Request :
Screenshot 2022-02-03 at 4 32 45 AM
</td>
<tr>
      <td>
Approve Withdraw Request by Bank :
Screenshot 2022-02-03 at 4 33 27 AM
</td>
<td>
Account Balance after Approval  from Bank:
Screenshot 2022-02-03 at 4 33 56 AM
</td>
  </tr>
</table>

### CODE REVIEW

**Comment by belelaritra** [comment]
Please let me know if there are any changes required @mbcse .
Also please add `JWOC` , `easy` both of these labels.

**Comment by mbcse** [comment]
@belelaritra Put this in a folder called BANK

**Comment by belelaritra** [comment]
@mbcse PTAL.

**Comment by mbcse** [comment]
@belelaritra Hey Please Fix the struct suggestion that I have given. Also sorry for the confusion, you have to put file in bank folder under ethereum folder.

**Comment by mbcse** [comment]
@belelaritra Thanks for the contribution!

**Pull request merged**
